# Generated by Django 2.0.5 on 2018-06-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTwo', '0002_auto_20180613_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
